# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-05-26 02:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_auto_20160525_2206'),
    ]

    operations = [
        migrations.RunSQL(
            [
                """
                CREATE TRIGGER story_search_update BEFORE INSERT OR UPDATE
                ON reader_story FOR EACH ROW EXECUTE PROCEDURE
                tsvector_update_trigger(search, 'pg_catalog.english', title, content);
                """,
                "UPDATE reader_story SET ident = ident;",
                "CREATE INDEX story_search_idx ON reader_story USING gin(search);",
            ],
            [
                "DROP TRIGGER story_search_update ON reader_story;",
                "DROP INDEX story_search_idx;",
            ]
        )
    ]
