# Generated by Django 2.2.5 on 2019-09-24 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0003_auto_20160525_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='story_count',
            field=models.IntegerField(default=0),
        ),
        migrations.RunSQL("""
            WITH counts AS (SELECT feed_id, count(id) AS num FROM reader_story GROUP BY feed_id)
            UPDATE reader_feed SET story_count = counts.num FROM counts WHERE id = counts.feed_id
        """, reverse_sql=migrations.RunSQL.noop),
    ]
