# Generated by Django 2.2.5 on 2019-09-25 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0004_feed_story_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='read_count',
            field=models.IntegerField(default=0),
        ),
        migrations.RunSQL("""
            WITH read_counts AS (
                SELECT
                    rs.user_id,
                    s.feed_id,
                    count(rs.id) AS read_count
                FROM
                    reader_readstory rs
                    INNER JOIN reader_story s ON s.id = rs.story_id
                WHERE
                    rs.is_read = true
                GROUP BY
                    rs.user_id,
                    s.feed_id
            )
            UPDATE reader_subscription s SET read_count = rc.read_count FROM read_counts rc
            WHERE s.feed_id = rc.feed_id AND s.user_id = rc.user_id;
        """, reverse_sql=migrations.RunSQL.noop)
    ]
