# Generated by Django 2.2.5 on 2019-09-25 01:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0005_subscription_read_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='date_published',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
