# Generated by Django 2.2.5 on 2019-09-25 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0006_auto_20190924_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='readstory',
            name='feed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='read_stories', to='reader.Feed'),
        ),
    ]
