# Generated by Django 2.2.5 on 2019-09-25 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0007_readstory_feed'),
    ]

    operations = [
        migrations.RunSQL("""
            UPDATE reader_readstory SET feed_id = s.feed_id FROM reader_story s WHERE story_id = s.id
        """, reverse_sql=migrations.RunSQL.noop),
    ]
